name = "tiktin2"
author = "znepb, AutiOne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b69a8087bcb64304602755429c3d1535adf268295b057138acf83f4da5ef7f7c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
